spring:
  application:
    name: 'quad-queue'
  datasource:
    url: jdbc:mysql://localhost:3306/quad_queue?useSSL=false
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 1986

quad-queue:
  configuration:
    executor:
      core-pool-size: 20
      max-pool-size: 30
      queue-capacity: 15

